<a href="https://colab.research.google.com/github/Alireza-Mohammadzade/Kamyar-Pub/blob/main/00_Pytorch_Fundamental_YT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ('Hello im exicted to learn PyTorch!')

Hello im exicted to learn PyTorch!


In [ ]:
!nvidia-smi

Tue Oct 22 19:53:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cpu


In [ ]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
print (scalar.ndim)

0


In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7 , 8])
#vector
#vector.ndim
#vector.shape

torch.Size([3])

In [ ]:
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
#MATRIX.ndim
#MATRIX.shape
MATRIX[0][1]

tensor(2)

In [ ]:
TENSOR = torch.tensor([[[1,2,3] ,
                        [4,5,6] ,
                        [7,8,9]  ], [[2,2,3] ,
                         [4,5,6] ,
                         [7,8,9]   ]])
TENSOR
TENSOR.ndim
TENSOR.shape
#TENSOR[1]

torch.Size([2, 3, 3])

In [ ]:
random_tensor = torch.rand(2,3,4)
random_tensor.shape

torch.Size([2, 3, 4])

In [ ]:
random_tensor_2 = torch.rand(size=(3,1))
random_tensor_2.shape
random_tensor_2

tensor([[0.5850],
        [0.7561],
        [0.4067]])

In [ ]:
zeros = torch.zeros(3,3)
ones = torch.ones(1,3)
ones
random_tensor_2*ones

tensor([[0.5850, 0.5850, 0.5850],
        [0.7561, 0.7561, 0.7561],
        [0.4067, 0.4067, 0.4067]])

In [ ]:
ones.dtype #default type float32

torch.float32

In [ ]:
a =torch.arange(start = 0, end = 1000 , step = 77 )
a

In [ ]:
b = torch.zeros_like(input=a)
b

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
c = torch.rand(size=(3,3) , dtype = torch.half , device = 'cpu' , requires_grad= False)
c = c.type(torch.double)
c.device

device(type='cpu')

In [ ]:
d = torch.rand(size = (3,3) , dtype = float , device ='cpu' , requires_grad = False)
c*d

tensor([[0.0988, 0.2239, 0.3788],
        [0.0070, 0.6105, 0.0460],
        [0.5271, 0.0876, 0.0702]], dtype=torch.float64)

In [ ]:
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.sub(tensor , 10)
torch.add(tensor , 10)
torch.mul(tensor , 10)
torch.div(tensor , 10)

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor_1 = torch.rand(size = (3,2,6,4))
tensor_2 = torch.rand(size = (3,2,4,7))
torch.matmul(tensor_1 , tensor_2).shape

torch.Size([3, 2, 6, 7])

In [ ]:
tensor_3 = torch.tensor([1,2,3])
torch.matmul(tensor_3 , tensor_3)
torch.mm(torch.tensor([[1,2,3]]) , torch.tensor([[1],[2],[3]])).shape # this only takes matrices # better to use matmul

torch.Size([1, 1])

In [ ]:
%%time
1+2

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.87 µs


3

In [ ]:
tensor_3 @ tensor_3 # another form of matmul

tensor(14)

In [ ]:
torch.tensor([[[1,2,3],
              [4,5,6]]]).T # transpose

tensor([[[1],
         [4]],

        [[2],
         [5]],

        [[3],
         [6]]])

In [ ]:
a = torch.arange(0, 100 , 10)
a = a.float()
a.min()
a.max()
a.mean()
a.sum()
a.argmax() # gives the index of max
a.argmin() # gives the index of min

tensor(0)

In [ ]:
b = torch.tensor([1,2,3,4])
b.reshape(1,4)
b.reshape(2,2)
c = b.view(4,1) # its similar to reshape but i shares the same memory with the original tensor
#c[0] = 5
c ,  b # when i changed the viewport of b it changed b itself too because they share the same memory! :D
torch.stack([b,b,b,b],dim=1) # 0 vertically and 1 horizontally idk about -1 and -2 :D
torch.vstack([b,b,b,b]) # like dim 0
torch.hstack([b,b,b,b]) # justt connects them horizonatlly not like dim 1
d = torch.tensor([[1,2,3,4]])
d.squeeze()# removes all 1 dimensions from the tensor
d.unsqueeze(dim=2) # creates another 1 dimension in the index of size
e = torch.rand(size=(1,2,3,4,1,6,34,1,5,1,1,17))
e.squeeze().size()
f = torch.rand(size=(1,3,5))
f
f.permute(2,0,1) # changes the size indexes it was 1 3 5 now its 5 1 3


tensor([[[0.8753, 0.0857, 0.4228]],

        [[0.3054, 0.9728, 0.3526]],

        [[0.0643, 0.9327, 0.9729]],

        [[0.5019, 0.5722, 0.1492]],

        [[0.5593, 0.4975, 0.2961]]])